### ISSUE TITLE
Support for League\CommonMark 2.0

### ISSUE THREAD

**Issue by monoteba** [simonvomeyser/commonmark-ext-lazy-image#2]
I tried to use your extension with the latest (2.0) version of CommonMark, but due to API changes it does not work.

I have upgraded the extension to work with the new version (using PHP 8.0.8), and everything appears to work. It is not battle tested, though!

Feel free to make use of my modified files: 
[LazyImage2.0.zip](https://github.com/simonvomeyser/commonmark-ext-lazy-image/files/6898966/LazyImage2.0.zip)

**Comment by RJFares** [comment]
+1

**Comment by usernotnull** [comment]
added your changes to PR: https://github.com/simonvomeyser/commonmark-ext-lazy-image/pull/4

**Comment by simonvomeyser** [comment]
hey @mortenblaa @usernotnull I finally found time to merge and publish the suggested update, everything should be fine and working now, I am closing this!

Thanks for the help and keep up the good work 🤜🤛

Simon vom Eyser
